---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Italian Translation Alliance"
keywords:    ""
description: "L’Italian Translation Alliance è un gruppo informale di giocatori di ruolo che si riconoscono nei valori di contenuto libero, condivisione, inclusività e collaborazione, il cui scopo è tradurre e diffondere liberamente e gratuitamente giochi di ruolo in lingua italiana."
source_link: ""
favicon:     "img/favicon.ico"
touch_icon:  "img/italian_translation_alliance_white.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  wall:      '#cf420f'
  ocra:      '#cf720f'

kramdown:
  auto_ids:  false

